version: '3'
services:

  official_serving_1_9_0:
    image: tensorflow/serving:1.9.0
    ports:
      - "8501:8500"
    environment:
      - MODEL_NAME=test_model
    volumes:
      - ./.fake-models/test_model:/models/test_model

  official_serving_1_10_0:
    image: tensorflow/serving:1.10.0
    ports:
      - "8502:8500"
    environment:
      - MODEL_NAME=test_model
    volumes:
      - ./.fake-models/test_model:/models/test_model

  official_serving_1_11_1:
    image: tensorflow/serving:1.11.1
    ports:
      - "8503:8500"
    environment:
      - MODEL_NAME=test_model
    volumes:
      - ./.fake-models/test_model:/models/test_model

  official_serving_1_12_3:
    image: tensorflow/serving:1.12.3
    ports:
      - "8504:8500"
    environment:
      - MODEL_NAME=test_model
    volumes:
      - ./.fake-models/test_model:/models/test_model

  official_serving_1_13_1:
    image: tensorflow/serving:1.13.1
    ports:
      - "8505:8500"
    environment:
      - MODEL_NAME=test_model
    volumes:
      - ./.fake-models/test_model:/models/test_model

  official_serving_1_14_0:
    image: tensorflow/serving:1.14.0
    ports:
      - "8506:8500"
    environment:
      - MODEL_NAME=test_model
    volumes:
      - ./.fake-models/test_model:/models/test_model

  official_serving_1_15_0:
    image: tensorflow/serving:1.15.0
    ports:
      - "8507:8500"
    environment:
      - MODEL_NAME=test_model
    volumes:
      - ./.fake-models/test_model:/models/test_model
