version: '3'
services:
  official_serving_1_6_1:
    image: tensorflow/serving:1.6.1
    ports:
      - "8501:8500"
    environment:
      - MODEL_NAME=test_model
    volumes:
      - ./.fake-models/test_model:/models/test_model
